//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EasyExcel.
//     Runtime Version: 4.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using UnityEngine;
using EasyExcel;

namespace EasyExcelGenerated
{
	[Serializable]
	public class Languages : EERowData
	{
		[SerializeField]
		private string _ID;
		public string ID { get { return _ID; } }

		[EEKeyField]
		[SerializeField]
		private string _Name;
		public string Name { get { return _Name; } }

		[SerializeField]
		private string _EN;
		public string EN { get { return _EN; } }

		[SerializeField]
		private string _RU;
		public string RU { get { return _RU; } }


		public Languages()
		{
		}

#if UNITY_EDITOR
		public Languages(List<List<string>> sheet, int row, int column)
		{
			TryParse(sheet[row][column++], out _ID);
			TryParse(sheet[row][column++], out _Name);
			TryParse(sheet[row][column++], out _EN);
			TryParse(sheet[row][column++], out _RU);
		}
#endif
		public override void OnAfterSerialized()
		{
		}
	}

	public class LocalizationSheet_Languages_Sheet : EERowDataCollection
	{
		[SerializeField]
		private List<Languages> elements = new List<Languages>();

		public override void AddData(EERowData data)
		{
			elements.Add(data as Languages);
		}

		public override int GetDataCount()
		{
			return elements.Count;
		}

		public override EERowData GetData(int index)
		{
			return elements[index];
		}

		public override void OnAfterSerialized()
		{
			foreach (var element in elements)
				element.OnAfterSerialized();
		}
	}
}
